dbs:
  - path: /opt/todoapp/db.sqlite3
    replicas:
      - type: s3
        bucket: ${R2_BUCKET}
        path: db.sqlite3
        endpoint: ${R2_ENDPOINT}
        access-key-id: ${LITESTREAM_ACCESS_KEY_ID}
        secret-access-key: ${LITESTREAM_SECRET_ACCESS_KEY}
        force-path-style: true
